### ISSUE TITLE
Tip is placed in wrong position when scrolling

### ISSUE THREAD

**Issue by irideas** [clair-design/clair#29]
Hi :
Tip is placed in wrong position when scrolling.
As follow image.
![image](https://user-images.githubusercontent.com/192851/48930357-f30a3f00-ef2a-11e8-9853-4a92bbbd8445.png)

**Comment by AngusFu** [comment]
This is a known issue. Since the main scrolling element in our doc site is not `<body>`.

Maybe we would fixed this issue later (however, not in schedule 😄 ).
